name: ntf_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_circular_text: ^0.3.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: 6.1.0
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/fonts/
